baseURL = "https://www.christinezhou.info"
languageCode = "en-us"
title = "Christine Zhou | Portfolio"
theme = "cz"
publishDir = "docs"
pluralizelisttitles = "false"

[markup.goldmark.renderer]
unsafe= true